/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI1 */

#ifndef _Included_JNI1
#define _Included_JNI1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI1
 * Method:    calcArea
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_JNI1_calcArea
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     JNI1
 * Method:    calcCentroid
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_JNI1_calcCentroid
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
