/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Ques2 */

#ifndef _Included_Ques2
#define _Included_Ques2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Ques2
 * Method:    randomArr1
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_Ques2_randomArr1
  (JNIEnv *, jobject, jint);

/*
 * Class:     Ques2
 * Method:    randomArr2
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_Ques2_randomArr2
  (JNIEnv *, jobject, jint);

/*
 * Class:     Ques2
 * Method:    calcSum
 * Signature: ([I[I)I
 */
JNIEXPORT jint JNICALL Java_Ques2_calcSum
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
